language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t baizhengquan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baizhengquan/docker-react npm run test