language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t baizhengquan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true baizhengquan/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-284719798604"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"